"""add_indexes_checkins_students_timestamps

Revision ID: 083bf596be01
Revises: 37a626400768
Create Date: 2026-04-16 17:02:04.121046

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '083bf596be01'
down_revision: Union[str, Sequence[str], None] = '37a626400768'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_checkins_checked_in_at', 'checkins', ['checked_in_at'], unique=False)
    op.create_index('idx_students_created_at', 'students', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_students_created_at', table_name='students')
    op.drop_index('idx_checkins_checked_in_at', table_name='checkins')
    # ### end Alembic commands ###
