"""check models sync

Revision ID: 1a8ec44a17b1
Revises: 6bcd42a41138
Create Date: 2026-03-11 18:00:07.393748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a8ec44a17b1'
down_revision: Union[str, Sequence[str], None] = '6bcd42a41138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_enrollments_opportunity_id'), table_name='enrollments')
    op.drop_index(op.f('idx_enrollments_period_id'), table_name='enrollments')
    op.drop_index(op.f('idx_enrollments_student_id'), table_name='enrollments')
    op.drop_constraint(op.f('uq_enrollment_student_opportunity'), 'enrollments', type_='unique')
    op.drop_constraint(op.f('uq_enrollment_student_period'), 'enrollments', type_='unique')
    op.drop_index(op.f('idx_opportunities_period_active'), table_name='opportunities')
    op.drop_index(op.f('idx_opportunities_period_id'), table_name='opportunities')
    op.drop_constraint(op.f('uq_students_matricula'), 'students', type_='unique')
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_students_matricula'), 'students', ['matricula'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_opportunities_period_id'), 'opportunities', ['period_id'], unique=False)
    op.create_index(op.f('idx_opportunities_period_active'), 'opportunities', ['period_id', 'is_active'], unique=False)
    op.create_unique_constraint(op.f('uq_enrollment_student_period'), 'enrollments', ['student_id', 'period_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_enrollment_student_opportunity'), 'enrollments', ['student_id', 'opportunity_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_enrollments_student_id'), 'enrollments', ['student_id'], unique=False)
    op.create_index(op.f('idx_enrollments_period_id'), 'enrollments', ['period_id'], unique=False)
    op.create_index(op.f('idx_enrollments_opportunity_id'), 'enrollments', ['opportunity_id'], unique=False)
    # ### end Alembic commands ###
