"""add student fields

Revision ID: 20139ef85cc9
Revises: afc3b18fadf5
Create Date: 2026-02-28 20:02:40.868876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20139ef85cc9'
down_revision: Union[str, Sequence[str], None] = 'afc3b18fadf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('matricula', sa.String(length=50), nullable=False))
    op.add_column('students', sa.Column('nombre', sa.String(length=120), nullable=False))
    op.add_column('students', sa.Column('apellido', sa.String(length=120), nullable=False))
    op.create_index(op.f('ix_students_matricula'), 'students', ['matricula'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_students_matricula'), table_name='students')
    op.drop_column('students', 'apellido')
    op.drop_column('students', 'nombre')
    op.drop_column('students', 'matricula')
    # ### end Alembic commands ###
