"""add timestamps to opportunities

Revision ID: 9e12dfffdece
Revises: 6bcd42a41138
Create Date: 2026-03-18 08:17:48.587568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e12dfffdece'
down_revision: Union[str, Sequence[str], None] = '6bcd42a41138'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('opportunities', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('opportunities', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunities', 'updated_at')
    op.drop_column('opportunities', 'created_at')
    # ### end Alembic commands ###
