"""add otp_codes and checkins tables

Revision ID: ac97ed44f2d0
Revises: 9e12dfffdece
Create Date: 2026-03-18 08:45:15.465360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac97ed44f2d0'
down_revision: Union[str, Sequence[str], None] = '9e12dfffdece'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checkins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('enrollment_id', sa.UUID(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('method', sa.String(length=50), nullable=True),
    sa.Column('device', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enrollment_id', name='uq_checkins_enrollment_id')
    )
    op.create_index('idx_checkins_enrollment_id', 'checkins', ['enrollment_id'], unique=False)
    op.create_table('otp_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('enrollment_id', sa.UUID(), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_otp_codes_enrollment_id', 'otp_codes', ['enrollment_id'], unique=False)
    op.create_index('idx_otp_codes_expires_at', 'otp_codes', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_otp_codes_expires_at', table_name='otp_codes')
    op.drop_index('idx_otp_codes_enrollment_id', table_name='otp_codes')
    op.drop_table('otp_codes')
    op.drop_index('idx_checkins_enrollment_id', table_name='checkins')
    op.drop_table('checkins')
    # ### end Alembic commands ###
