"""otp_checkins_migrate_to_student_id

Revision ID: f79c88cd9244
Revises: ac97ed44f2d0
Create Date: 2026-03-19 08:53:48.408309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f79c88cd9244'
down_revision: Union[str, Sequence[str], None] = 'ac97ed44f2d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkins', sa.Column('student_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('idx_checkins_enrollment_id'), table_name='checkins')
    op.drop_constraint(op.f('uq_checkins_enrollment_id'), 'checkins', type_='unique')
    op.create_index('idx_checkins_student_id', 'checkins', ['student_id'], unique=False)
    op.create_unique_constraint('uq_checkins_student_id', 'checkins', ['student_id'])
    op.drop_constraint(op.f('checkins_enrollment_id_fkey'), 'checkins', type_='foreignkey')
    op.create_foreign_key(None, 'checkins', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_column('checkins', 'enrollment_id')
    op.add_column('otp_codes', sa.Column('student_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('idx_otp_codes_enrollment_id'), table_name='otp_codes')
    op.create_index('idx_otp_codes_student_id', 'otp_codes', ['student_id'], unique=False)
    op.drop_constraint(op.f('otp_codes_enrollment_id_fkey'), 'otp_codes', type_='foreignkey')
    op.create_foreign_key(None, 'otp_codes', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_column('otp_codes', 'enrollment_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_codes', sa.Column('enrollment_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'otp_codes', type_='foreignkey')
    op.create_foreign_key(op.f('otp_codes_enrollment_id_fkey'), 'otp_codes', 'enrollments', ['enrollment_id'], ['id'], ondelete='CASCADE')
    op.drop_index('idx_otp_codes_student_id', table_name='otp_codes')
    op.create_index(op.f('idx_otp_codes_enrollment_id'), 'otp_codes', ['enrollment_id'], unique=False)
    op.drop_column('otp_codes', 'student_id')
    op.add_column('checkins', sa.Column('enrollment_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'checkins', type_='foreignkey')
    op.create_foreign_key(op.f('checkins_enrollment_id_fkey'), 'checkins', 'enrollments', ['enrollment_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_checkins_student_id', 'checkins', type_='unique')
    op.drop_index('idx_checkins_student_id', table_name='checkins')
    op.create_unique_constraint(op.f('uq_checkins_enrollment_id'), 'checkins', ['enrollment_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_checkins_enrollment_id'), 'checkins', ['enrollment_id'], unique=False)
    op.drop_column('checkins', 'student_id')
    # ### end Alembic commands ###
